import {
  pgTable,
  serial,
  integer,
  text,
  timestamp,
  boolean,
  index,
} from "drizzle-orm/pg-core";
import { storiesTable } from "./stories";

/**
 * Branching chapters tree.
 *
 * Replaces the legacy `stories.full_text` "## heading"-delimited
 * concatenation with first-class chapter rows that can have siblings
 * (alternate continuations / "What if?" forks). Exactly one chapter at
 * each tree level is marked `is_canonical = true`; following the
 * canonical chain from the root produces the linear story shown by
 * default. `stories.full_text` is kept as a denormalized read-only
 * mirror of the canonical path so legacy endpoints (PDF, audio, comments
 * counters, etc.) keep working unchanged.
 *
 * `parent_chapter_id` is null for the first chapter (root). `position`
 * orders siblings deterministically when two branches were generated in
 * the same request. `branch_label` is a short user-visible name like
 * "What if Mira refuses?" — auto-generated by the LLM when forking.
 */
export const chaptersTable = pgTable(
  "chapters",
  {
    id: serial("id").primaryKey(),
    storyId: integer("story_id")
      .notNull()
      .references(() => storiesTable.id, { onDelete: "cascade" }),
    parentChapterId: integer("parent_chapter_id"),
    title: text("title").notNull().default(""),
    branchLabel: text("branch_label").notNull().default(""),
    text: text("text").notNull().default(""),
    position: integer("position").notNull().default(0),
    isCanonical: boolean("is_canonical").notNull().default(true),
    // Optional ownership: who wrote this chapter. Lets co-authors
    // contribute alternate branches without losing attribution.
    authorUserId: integer("author_user_id"),
    authorHandle: text("author_handle"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (table) => ({
    storyIdx: index("chapters_story_idx").on(table.storyId),
    parentIdx: index("chapters_parent_idx").on(table.parentChapterId),
    storyParentPosIdx: index("chapters_story_parent_pos_idx").on(
      table.storyId,
      table.parentChapterId,
      table.position,
    ),
  }),
);

export type Chapter = typeof chaptersTable.$inferSelect;
export type InsertChapter = typeof chaptersTable.$inferInsert;
